### ISSUE TITLE
Error while switching states: blocks are not set

### ISSUE THREAD

**Issue by krisjenner** [mattysweeps/SurvivalGames#4]
Hey, I believe I'm following the instructions correctly but upon doing /ssg ready demo I get the error in the title.

**Comment by mattysweeps** [comment]
Thanks for the issue @krisjenner 
What version of the plugin are you running?

This error normally means the `/ssg set blocks demo` command hasn't been executed yet.

The command is required due to a current limitation with Survival games config: the blocks themselves are not saved in the yaml config, so the have to be "set" in memory so when the game starts, they can be set to their initial state.

I want to remove the `/ssg set blocks` command because I think it's tedious and unnecessary. I've opened #3 to track that progress.

I'm also working to improve the demo command in general, which #2 will track.

Let me know if the `/ssg set blocks` command fixes that error.

**Comment by krisjenner** [comment]
Hey thanks it does fix the error! But can I ask what the greater and lesser boundary represent? Is it two diagonal corners of a box for the world border?

**Comment by mattysweeps** [comment]
Yup, you are correct. You should be able to set those with the `/ssg set boundary command, which I think will figure out which one to update. There might be a side effect that the boundary can only expand after it is set, another things for me to look in to.

You should be able to use /ssg unset boundary to reset them.

And /ssg print boundary to view their values

**Comment by mattysweeps** [comment]
@krisjenner Since the set blocks command resolved your issue and since I created other tickets for the improvements we discussed here, I'm going to close this.
