### ISSUE TITLE
Permission nodes aren't prefixed with "SSG"

### ISSUE THREAD

**Issue by krisjenner** [mattysweeps/SurvivalGames#7]
It appears the permission nodes for the SSG commands are listed as "add" "list" "demo" etc when they should be ssg.command.add or something - hope this helps

**Comment by mattysweeps** [comment]
@krisjenner Thanks for the issue. It should be fixed on [v1.0.11](https://github.com/mattysweeps/SurvivalGames/releases/tag/v1.0.11), let me know if it isn't.

This was due to an ordering problem on initialization of the commands. The fix I applied was to set the children of a command at a second step, so the parents could be initialized first before adding the reference to the children.

**Comment by mattysweeps** [comment]
And as of 1.1.3 it should be really fixed
